import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillGithub, AiFillLinkedin } from 'react-icons/ai';
import Image from "next/legacy/image";
import avatarme from "/public/avatarme.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Zhiyad Harith Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons uppercase">developedbyzhd</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Zhiyad Harith</h2>
            <h3 className="text-2xl py-2">Aspiring Frontend Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">Hello! This is my portfolio to showcase the projects I've worked on to potential employers. Thank you for taking your time!</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={avatarme} />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">A little bit about myself</h3>
            <p className="text-md py-2 leading-8 text-gray-80">As a self-taught software enthusiast with a background in Quantity Surveying, I have been dedicated to expanding my knowledge and skills in the field of web development. Over the past three months, I have immersed myself in the study of JavaScript, React.js, HTML, and CSS, and have built several projects based on YouTube tutorials, which have allowed me to apply my newfound understanding of the fundamental components of React.js and its role in creating responsive web designs.

My passion for software engineering was sparked after working for three years as a Quantity Surveyor, and I now aspire to become a highly skilled software developer, focusing either on frontend development or full-stack expertise. I believe that continuous growth and improvement are essential in this field, and I am committed to honing my skills and expanding my knowledge to the best of my ability.

I am eager to apply my skills and expertise to real-world projects, and I am confident that my background and dedication will make me a valuable asset to any team. I look forward to the opportunity to bring my passion and experience to the table, and to make a positive impact in the field of software development.</p>
          </div>
        </section>
      </main>
    </div>
  );
}

