import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Zhiyad Harith Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <section className="bg-blue-700">

        </section>
      </main>
    </div>
  );
}
